# -*- coding: utf-8 -*-
"""EntregableU3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jPeZvRD_F4ugyjIciWXdc5EUrMl82P6p
"""

import pandas as pd

sedes = pd.read_csv('/content/sedes.csv')
empleados = pd.read_csv('/content/empleados.csv')
proveedores = pd.read_csv('/content/proveedores.csv')
clientes = pd.read_csv('/content/clientes.csv')
vehiculos = pd.read_csv('/content/vehiculos.csv')
ventas = pd.read_csv('/content/ventas.csv')
revisiones = pd.read_csv('/content/revisiones.csv')

def limpiar_maestra(df, id_col):
    df = df.drop_duplicates(subset=[id_col])
    df = df.dropna(subset=[id_col])
    return df

sedes = limpiar_maestra(sedes, 'id_sede')
sedes['nombre_sede'] = sedes['nombre_sede'].str.upper()
dummy_sede = pd.DataFrame([{
    'id_sede': 0,
    'nombre_sede': 'SEDE NO ASIGNADA',
    'ubicacion': 'SIN DEFINIR'
}])
sedes = pd.concat([sedes, dummy_sede], ignore_index=True)

sedes.head()

empleados = limpiar_maestra(empleados, 'id_empleado')
empleados['nombre'] = empleados['nombre'].str.upper()
empleados['id_sede'] = empleados['id_sede'].fillna(0).astype(int)
dummy_empleado = pd.DataFrame([{'id_empleado': 0, 'nombre': 'EMPLEADO GENERICO', 'cargo': 'N/A', 'id_sede': 0}])
empleados = pd.concat([empleados, dummy_empleado], ignore_index=True)

proveedores = limpiar_maestra(proveedores, 'id_proveedor')
proveedores['nombre_proveedor'] = proveedores['nombre_proveedor'].str.upper()
proveedores['contacto'] = proveedores['contacto'].fillna('Sin contacto')
nuevo_proveedor = pd.DataFrame([{
    'id_proveedor': 0,
    'nombre_proveedor': 'SIN PROVEEDOR',
    'contacto': '00000000'
}])
proveedores = pd.concat([proveedores, nuevo_proveedor], ignore_index=True)

proveedores.head()

clientes = limpiar_maestra(clientes, 'id_cliente')
clientes['nombre'] = clientes['nombre'].str.upper()
clientes['correo'] = clientes['correo'].fillna('sin_correo@autofuturo.com')
clientes['telefono'] = clientes['telefono'].fillna('0000000')
dummy_cliente = pd.DataFrame([{'id_cliente': 0, 'nombre': 'CLIENTE NO IDENTIFICADO', 'correo': 'desconocido@autofuturo.com', 'telefono': '0000000'}])
clientes = pd.concat([clientes, dummy_cliente], ignore_index=True)

clientes.head()

vehiculos = limpiar_maestra(vehiculos, 'id_vehiculo')
vehiculos['marca'] = vehiculos['marca'].str.upper()
vehiculos['ano'] = vehiculos['ano'].fillna(0).astype(int)
vehiculos['precio'] = vehiculos['precio'].fillna(0)
vehiculos['id_proveedor'] = vehiculos['id_proveedor'].fillna(0).astype(int)
dummy_vehiculo = pd.DataFrame([{
    'id_vehiculo': 0, 'marca': 'GENERICO', 'modelo': 'NO IDENTIFICADO',
    'ano': 0, 'precio': 0.0, 'estado': 'NO ESPECIFICADO', 'id_proveedor': 0, 'placa': '000-000'
}])
vehiculos = pd.concat([vehiculos, dummy_vehiculo], ignore_index=True)

vehiculos.head()

ventas = limpiar_maestra(ventas, 'id_venta')
ventas['fecha_venta'] = pd.to_datetime(ventas['fecha_venta'], errors='coerce')
ventas['monto_total'] = ventas['monto_total'].fillna(0)
ventas['id_cliente'] = ventas['id_cliente'].fillna(0).astype(int)
ventas['id_vehiculo'] = ventas['id_vehiculo'].fillna(0).astype(int)
ventas['id_empleado'] = ventas['id_empleado'].fillna(0).astype(int)

ventas.loc[~ventas['id_cliente'].isin(clientes['id_cliente']), 'id_cliente'] = 0
ventas.loc[~ventas['id_vehiculo'].isin(vehiculos['id_vehiculo']), 'id_vehiculo'] = 0
ventas.loc[~ventas['id_empleado'].isin(empleados['id_empleado']), 'id_empleado'] = 0

ventas.head()

revisiones = limpiar_maestra(revisiones, 'id_revision')
revisiones['fecha_revision'] = pd.to_datetime(revisiones['fecha_revision'], errors='coerce')
revisiones = revisiones.dropna(subset=['id_vehiculo', 'id_empleado', 'fecha_revision'])
revisiones['descripcion'] = revisiones['descripcion'].fillna('Sin observaciones')

revisiones.head()

sedes.to_csv('sedes_limpio.csv', index=False)
empleados.to_csv('empleados_limpio.csv', index=False)
proveedores.to_csv('proveedores_limpio.csv', index=False)
clientes.to_csv('clientes_limpio.csv', index=False)
vehiculos.to_csv('vehiculos_limpio.csv', index=False)
ventas.to_csv('ventas_limpio.csv', index=False)
revisiones.to_csv('revisiones_limpio.csv', index=False)